"""M-RI-17 acceptance tests: belief pass over the contested set.

Pins the frozen preregistration and every discretionary declaration it
makes (mass assignments, alias predicate source, placeholder list,
frozen input manifest), the golden artifacts (byte-identical
regeneration), the Dolton known-answer commitment, and the contract
MUSTs (absence never reported as conflict; per-observation provenance;
mandated per-parcel wording; Recorder banners carried).
"""
from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from decimal import Decimal
from pathlib import Path

import pytest

from rights_events.policy import CLAIM_MASS
from rights_events.schema import EPType

from audit.belief import mapping
from audit.belief.run import (
    KNOWN_ANSWER_CONFLICT,
    KNOWN_ANSWER_PIN14,
    run_pass,
)

ROOT = Path(__file__).resolve().parents[1]
PREREG = ROOT / "audit" / "prereg" / "M-RI-17-PREREGISTRATION.md"
OUT_DIR = ROOT / "audit" / "belief" / "out"
DETERMINATION = ROOT / "audit" / "out" / "belief-determination.md"

# The preregistration is FROZEN (committed before audit/belief/ existed).
# Any byte changing after that commit is the failure happening in real
# time — this pin makes a silent edit fail the suite.
PREREG_SHA256 = (
    "08f83a586811b2267ab6dfc0fa5cd2c1e1c8709406a25ef976bfa6db3d77f82c")

# Golden artifacts: regenerated byte-identically from the frozen
# snapshots by python -m audit.belief (double-run and PYTHONHASHSEED
# cross-checks in the DONE report).
GOLDEN_SHA256 = {
    OUT_DIR / "parcels_belief.ri":
        "9aca296c3d2e6d387c0441aef6a031cc26dd8e621419fd997660173538ff5ee2",
    OUT_DIR / "belief_objects.json":
        "2ef09f1fb0139eaf2f364d1e7500dd93f1afaac1984565f772ab4b03faeb4aaf",
    DETERMINATION:
        "49a1326f12f8ffac638b5b72cd832ff1872eba53e14d7c7f3e434e28d47edddd",
}

ABSENCE_SENTENCE = "no counter-claim was found in the captured snapshots"
COMPLETENESS_SENTENCE = ("a records-completeness finding about the "
                         "client's bookkeeping question")
PLACEHOLDER_PIN14 = "29302020160000"
BANNERED_PINS = ("25-29-323-064-0000", "25-30-207-023-0000")


def _sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


@pytest.fixture(scope="module")
def regenerated(tmp_path_factory):
    """One full in-process re-run of the pass into a temp directory."""
    tmp = tmp_path_factory.mktemp("m_ri_17")
    summary = run_pass(out_dir=tmp / "out",
                       determination_path=tmp / "belief-determination.md")
    return tmp, summary


@pytest.fixture(scope="module")
def committed_objects():
    return json.loads((OUT_DIR / "belief_objects.json")
                      .read_text(encoding="ascii"))


class TestFrozenDeclarations:
    def test_preregistration_frozen(self):
        assert _sha(PREREG) == PREREG_SHA256, (
            "PREREGISTRATION bytes changed after freeze — stop condition")

    def test_mass_declarations_pinned_three_ways(self):
        # Prereg (sha above), mirror constants, and frozen policy must
        # all agree; a silent edit of any one fails here.
        assert mapping.STATUTORY_CLAIM_MASS == Decimal("0.6")
        assert mapping.DISPUTE_CLAIM_MASS == Decimal("0")
        assert CLAIM_MASS[EPType.STATUTORY_REGISTRY] == Decimal("0.6")
        assert CLAIM_MASS[EPType.CRYPTOGRAPHICALLY_SIGNED] == \
            Decimal("0.55")
        assert CLAIM_MASS[EPType.THIRD_PARTY_ATTESTED] == Decimal("0.45")
        assert CLAIM_MASS[EPType.SELF_ASSERTED] == Decimal("0.3")
        text = PREREG.read_text(encoding="utf-8")
        for declared in ("| statutory_registry | **0.6** |",
                         "| cryptographically_signed | 0.55 |",
                         "| third_party_attested | 0.45 |",
                         "| self_asserted | 0.3 |"):
            assert declared in text

    def test_input_manifest_pinned(self):
        manifest = mapping.load_manifest()
        assert len(manifest["parcels"]) == 44
        verdicts = [p["verdict"] for p in manifest["parcels"]]
        assert verdicts.count("CONTRADICTED") == 9
        assert verdicts.count("AMBIGUOUS") == 35

    def test_alias_predicate_pinned_to_attestations(self):
        norms = mapping.load_alias_norms()
        # Attested variants canonicalize; the 'uncertain' string does not.
        for attested in ("SO SUB LAND/BK/DEV", "SO SUB LAND BANK",
                         "SOUTH SUBURBAN LAND BANK",
                         "SOUTH SUBURBAN LAND BANK AND DEVELOPMENT "
                         "AUTHORITY"):
            assert mapping.canonical_name(attested, norms) == \
                mapping.CANONICAL_CLIENT
        for uncertain in ("SUBURBAN LAND BANK &amp;",
                          "SUBURBAN LAND BANK &AMP;"):
            assert mapping.canonical_name(uncertain, norms) == uncertain
        assert mapping.canonical_name(None, norms) is None

    def test_placeholder_list_pinned(self):
        assert mapping.PLACEHOLDER_OWNER_STRINGS == ("TAXPAYER OF",)


class TestGoldens:
    def test_committed_artifacts_match_pins(self):
        for path, expected in GOLDEN_SHA256.items():
            assert _sha(path) == expected, f"golden drifted: {path}"

    def test_regeneration_is_byte_identical(self, regenerated):
        tmp, _summary = regenerated
        pairs = [
            (tmp / "out" / "parcels_belief.ri",
             OUT_DIR / "parcels_belief.ri"),
            (tmp / "out" / "belief_objects.json",
             OUT_DIR / "belief_objects.json"),
            (tmp / "belief-determination.md", DETERMINATION),
        ]
        for fresh, committed in pairs:
            assert fresh.read_bytes() == committed.read_bytes(), (
                f"regenerated {fresh.name} differs from committed bytes")


class TestKnownAnswer:
    def test_dolton_reproduces_c2_conflict_exactly(self, regenerated,
                                                   committed_objects):
        _tmp, summary = regenerated
        assert summary["known_answer_ok"]
        assert Decimal(summary["dolton_conflict"]) == \
            KNOWN_ANSWER_CONFLICT
        entry = next(p for p in committed_objects["parcels"]
                     if p["pin14"] == KNOWN_ANSWER_PIN14)
        assert Decimal(entry["conflict_mass"]) == Decimal("0.91296")
        assert Decimal(entry["unresolved_mass"]) == Decimal("0.01024")
        assert entry["frame_size"] == 5
        singles = {Decimal(entry["mass"][h]) for h in entry["frame"]}
        assert singles == {Decimal("0.01536")}


class TestContractMusts:
    def test_absence_never_reported_as_conflict(self, committed_objects):
        singles = [p for p in committed_objects["parcels"]
                   if p["frame_size"] == 1]
        assert singles, "expected single-claim parcels in this set"
        for parcel in singles:
            assert Decimal(parcel["conflict_mass"]) == 0, parcel["pin"]
            assert Decimal(parcel["unresolved_mass"]) == 1, parcel["pin"]

    def test_omega_and_conflict_separated_in_words(self,
                                                   committed_objects):
        text = DETERMINATION.read_text(encoding="utf-8")
        singles = sum(1 for p in committed_objects["parcels"]
                      if p["frame_size"] == 1)
        assert text.count(ABSENCE_SENTENCE) == singles
        contradicted_singles = sum(
            1 for p in committed_objects["parcels"]
            if p["frame_size"] == 1
            and p["m_ri_16_verdict"] == "CONTRADICTED")
        assert text.count(COMPLETENESS_SENTENCE) == contradicted_singles
        # Every parcel section separates the two states explicitly.
        assert text.count("m(Ω) =") >= 44
        assert text.count("m(∅) =") >= 44

    def test_every_observation_traces_to_source(self, committed_objects):
        for parcel in committed_objects["parcels"]:
            for event in parcel["contributing_events"]:
                assert event["source_url"].startswith("https://"), event
                assert len(event["observed_date"]) == 10, event
                if event["event_id"].startswith("cook:roll:"):
                    cite = event["snapshot_citation"]
                    assert cite["dataset_id"] == "3723-97qp"
                    assert cite["row"]["owner_address_name"]
                    assert cite["retrieved_date"] == "2026-08-02"

    def test_placeholder_produces_no_observation(self, committed_objects):
        entry = next(p for p in committed_objects["parcels"]
                     if p["pin14"] == PLACEHOLDER_PIN14)
        assert entry["placeholder_drops"] and \
            entry["placeholder_drops"][0]["owner_address_name"] == \
            "TAXPAYER OF"
        assert not any(e["event_id"].startswith("cook:roll:")
                       for e in entry["contributing_events"])
        for parcel in committed_objects["parcels"]:
            for hyp in parcel["frame"]:
                assert "TAXPAYER OF" not in hyp

    def test_recorder_banners_carried(self, committed_objects):
        text = DETERMINATION.read_text(encoding="utf-8")
        for pin in BANNERED_PINS:
            entry = next(p for p in committed_objects["parcels"]
                         if p["pin"] == pin)
            assert entry["recorder_banner"] is True
            assert (f"### {pin} — M-RI-16 CONTRADICTED (D3) · "
                    f"**RECORDER BANNER — docs 2401822036/37**") in text
        others = [p for p in committed_objects["parcels"]
                  if p["pin"] not in BANNERED_PINS]
        assert all(p["recorder_banner"] is False for p in others)

    def test_all_44_parcels_present_and_counted(self, regenerated,
                                                committed_objects):
        _tmp, summary = regenerated
        assert summary["parcels"] == 44
        assert sum(summary["counts"].values()) == 44
        assert len(committed_objects["parcels"]) == 44


class TestReplay:
    def test_unchanged_replay_cli_verifies_dolton(self):
        result = subprocess.run(
            [sys.executable, "-m", "rights_events.replay",
             "--run", str(OUT_DIR / "parcels_belief.ri"),
             "--subject", f"parcel:{KNOWN_ANSWER_PIN14}"],
            cwd=ROOT, capture_output=True, text=True, timeout=120)
        assert result.returncode == 0, result.stdout + result.stderr
        assert "REPLAY: OK" in result.stdout
