"""Scaffold a new rigorous domain build from the forge library.

Usage (from the repo root):

    python forge/scaffold.py <domain-name> [--dest DIR] [--date YYYY-MM-DD]

Generates, into the EXISTING reference-implementation structure (never a
parallel root-level tree — operator amendment A2, forge/INVENTORY.md §9):

    reference-implementation/contracts/<domain>/CONTRACT.md    (from template)
    reference-implementation/contracts/<domain>/PREREG.md      (from template)
    reference-implementation/contracts/<domain>/SCOREBOARD.md  (from template)
    reference-implementation/rights_events/adapters/<domain>.py  (from skeleton)
    reference-implementation/tests/test_<domain>_gates.py     (smoke suite that
                                                fails until the adapter is real)

Pure stdlib. Idempotent: refuses to overwrite — if ANY target exists the run
fails before writing anything. Exit codes: 0 generated and validated,
1 refused or validation failed, 2 usage error.
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import date
from pathlib import Path

FORGE = Path(__file__).resolve().parent
REPO_ROOT = FORGE.parent
DEFAULT_DEST = REPO_ROOT / "reference-implementation"

_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")

_SMOKE_TEMPLATE = '''"""Gate smoke suite for the {domain} build. GENERATED by forge/scaffold.py.

This suite is the scaffold's proof of engine wiring, and it FAILS BY DESIGN
until the adapter is implemented (test-scoreboard-as-endpoint: tests are the
finish line, forge/PATTERNS.md #3). Replace it with the real gate tests named
in contracts/{domain}/SCOREBOARD.md once parse_events() is real.
"""

import pytest

from rights_events.schema import EPType, EventType, RightsEvent


def test_engine_wiring():
    """PASSES immediately: the scaffold sits on the proven engine unchanged."""
    event = RightsEvent(
        event_id="wiring:{domain}:1",
        event_type=EventType.CHAIN_ASSERTION,
        subject_ids=("{domain}:wiring-check",),
        claimant="scaffold-wiring-check",
        claim={{"note": "generated wiring check, not domain data"}},
        ep_type=EPType.SELF_ASSERTED,
        source_url="https://example.invalid/scaffold-wiring-check",
        observed_date="2026-01-01",
    )
    assert RightsEvent.from_dict(event.to_dict()) == event


def test_adapter_produces_events():
    """FAILS with a clear message until the adapter is implemented."""
    from rights_events.adapters.{domain} import parse_events

    try:
        events = parse_events("{{}}")
    except NotImplementedError as exc:
        pytest.fail(f"ADAPTER NOT IMPLEMENTED: {{exc}}")
    assert isinstance(events, list) and all(
        isinstance(e, RightsEvent) for e in events), (
        "parse_events() must return list[RightsEvent]")
'''


def _substitute(text: str, domain: str, run_date: str) -> str:
    contract_id = domain.upper().replace("_", "-")
    return (text
            .replace("{{CONTRACT_ID}}", contract_id)
            .replace("{{ONE_LINE_TITLE}}",
                     f"{domain} domain build (one line — fill in)")
            .replace("{{contract-slug}}", domain.replace("_", "-"))
            .replace("{{YYYY-MM-DD}}", run_date))


def required_headings() -> list[str]:
    """The template's `## ` headings, in order — the closed section set."""
    template = (FORGE / "templates" / "CONTRACT.template.md").read_text(
        encoding="utf-8")
    return [line for line in template.splitlines() if line.startswith("## ")]


def validate_contract(path: Path) -> list[str]:
    """Validate a generated CONTRACT.md against the template structure.

    Returns a list of problems (empty = valid): every template heading must
    be present, in template order.
    """
    lines = path.read_text(encoding="utf-8").splitlines()
    headings = [line for line in lines if line.startswith("## ")]
    problems = []
    expected = required_headings()
    missing = [h for h in expected if h not in headings]
    for h in missing:
        problems.append(f"missing required section: {h!r}")
    present_expected = [h for h in expected if h in headings]
    in_order = [h for h in headings if h in expected]
    if in_order != present_expected:
        problems.append(
            f"sections out of template order: {in_order} != {present_expected}")
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python forge/scaffold.py",
        description="Scaffold a new rigorous domain build "
                    "(contract + prereg + scoreboard + adapter + smoke suite).")
    parser.add_argument("domain", help="new domain name, [a-z][a-z0-9_]*")
    parser.add_argument("--dest", default=str(DEFAULT_DEST),
                        help="reference-implementation directory to generate "
                             "into (default: the one beside forge/)")
    parser.add_argument("--date", default=date.today().isoformat(),
                        help="date stamped into generated headers "
                             "(default: today; pass explicitly for "
                             "reproducible output)")
    args = parser.parse_args(argv)

    domain = args.domain
    if not _NAME_RE.match(domain):
        print(f"REFUSED: domain name {domain!r} must match [a-z][a-z0-9_]*")
        return 2

    dest = Path(args.dest).resolve()
    # Amendment A2 guard: generate only into an existing engine tree, never
    # a parallel structure.
    anchors = ("ri_core", "rights_events/adapters", "tests", "contracts")
    missing_anchors = [a for a in anchors if not (dest / a).is_dir()]
    if missing_anchors:
        print(f"REFUSED: {dest} is not a reference-implementation tree "
              f"(missing: {', '.join(missing_anchors)}). scaffold.py never "
              f"creates parallel directory structures.")
        return 1

    contract_dir = dest / "contracts" / domain
    targets = {
        contract_dir / "CONTRACT.md":
            FORGE / "templates" / "CONTRACT.template.md",
        contract_dir / "PREREG.md":
            FORGE / "templates" / "PREREG.template.md",
        contract_dir / "SCOREBOARD.md":
            FORGE / "templates" / "SCOREBOARD.template.md",
        dest / "rights_events" / "adapters" / f"{domain}.py":
            FORGE / "adapters" / "new_domain.py",
    }
    smoke_path = dest / "tests" / f"test_{domain}_gates.py"

    existing = [p for p in [*targets, smoke_path, contract_dir] if p.exists()]
    if existing:
        print("REFUSED: refusing to overwrite existing paths "
              "(idempotence rule):")
        for p in existing:
            print(f"  {p}")
        return 1

    contract_dir.mkdir(parents=True)
    written = []
    for target, source in targets.items():
        text = source.read_text(encoding="utf-8")
        if source.name == "new_domain.py":
            text = text.replace("new_domain", domain)
        else:
            text = _substitute(text, domain, args.date)
        target.write_text(text, encoding="utf-8", newline="\n")
        written.append(target)
    smoke_path.write_text(_SMOKE_TEMPLATE.format(domain=domain),
                          encoding="utf-8", newline="\n")
    written.append(smoke_path)

    problems = validate_contract(contract_dir / "CONTRACT.md")

    print(f"Scaffolded domain {domain!r} into {dest}:")
    for p in written:
        print(f"  {p.relative_to(dest)}")
    print()
    if problems:
        print("CONTRACT.md TEMPLATE VALIDATION: FAILED")
        for problem in problems:
            print(f"  {problem}")
        return 1
    print("CONTRACT.md template validation: OK "
          f"({len(required_headings())} required sections present, in order)")
    print()
    print("Next (the <15-minute path, timed in forge/README.md):")
    print(f"  1. Fill contracts/{domain}/CONTRACT.md — every {{{{...}}}}.")
    print(f"  2. Fill contracts/{domain}/PREREG.md and COMMIT IT before "
          f"touching any data.")
    print(f"  3. Run the smoke suite: pytest tests/test_{domain}_gates.py -q")
    print(f"     (one PASS = engine wired; one FAIL = adapter awaits you)")
    print(f"  4. Implement rights_events/adapters/{domain}.py per its "
          f"docstring's six declarations.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
