"""Gate smoke suite for the demo_fixture build. GENERATED by forge/scaffold.py.

This suite is the scaffold's proof of engine wiring, and it FAILS BY DESIGN
until the adapter is implemented (test-scoreboard-as-endpoint: tests are the
finish line, forge/PATTERNS.md #3). Replace it with the real gate tests named
in contracts/demo_fixture/SCOREBOARD.md once parse_events() is real.
"""

import pytest

from rights_events.schema import EPType, EventType, RightsEvent


def test_engine_wiring():
    """PASSES immediately: the scaffold sits on the proven engine unchanged."""
    event = RightsEvent(
        event_id="wiring:demo_fixture:1",
        event_type=EventType.CHAIN_ASSERTION,
        subject_ids=("demo_fixture:wiring-check",),
        claimant="scaffold-wiring-check",
        claim={"note": "generated wiring check, not domain data"},
        ep_type=EPType.SELF_ASSERTED,
        source_url="https://example.invalid/scaffold-wiring-check",
        observed_date="2026-01-01",
    )
    assert RightsEvent.from_dict(event.to_dict()) == event


def test_adapter_produces_events():
    """FAILS with a clear message until the adapter is implemented."""
    from rights_events.adapters.demo_fixture import parse_events

    try:
        events = parse_events("{}")
    except NotImplementedError as exc:
        pytest.fail(f"ADAPTER NOT IMPLEMENTED: {exc}")
    assert isinstance(events, list) and all(
        isinstance(e, RightsEvent) for e in events), (
        "parse_events() must return list[RightsEvent]")
